<a href="https://colab.research.google.com/github/Md-Refat-Hosain/Practice-data-codes-python-/blob/main/f_regression_and_f_score_%2C_p_values_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import statistics as st

# Libraries For Text

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')



from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
# Read dataset

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Udemy ds course datasets/Students2.csv')
df

Hours  sHours  hoursplayed  income  distance  calories  Marks
0       0       6            6     146         9      2491     34
1       1       7            2     112         5      2303     36
2       1       6            1      84         7      2475     33
3       1       8            5     134         0      2282     39
4       1       8            5     104         8      2359     42
5       2       8            4      80         1      2354     45
6       2       6            3      93         0      2943     38
7       3       6            3      83         7      2119     45
8       3       7            6     139         1      2511     53
9       3       7            5     138        10      2666     46
10      3       8            5      98         2      2934     56
11      4       8            1      90         0      2838     59
12      4       7            3     140         7      2102     55
13      4       7            6     144         3      2560     56
14      5       8            2     144         5      2068     72
15      5       6            2     119         6      2541     59
16      6       6            1     140         6      2690     62
17      6       7            1      85         3      2956     71
18      7       8            2     140         8      2239     78
19      7       8            6     107         0      2703     88
20      7       6            5      85         7      2603     61
21      7       6            3     109         0      2031     74
22      8       7            5     108         0      2885     71
23      8       8            1     150         8      2153     89
24      9       8            4     150         9      2384     82
25      9       5            5      84        10      2882     67
26      9       8            5     127         5      2271     89
27     10       8            6      95         6      2264     81
28     10       8            5      72         5      2522     82
29     11       7            3      89         3      2279     79

In [4]:
# Split columns into X indp. and Y dpend. variables

In [5]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [6]:
# Model import and train

In [7]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

In [8]:
# Fit data into model

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size= .3 , random_state= 42 )

In [10]:
lr.fit(X_train , y_train)

LinearRegression()

In [11]:
y_pred = lr.predict(X_test)

In [12]:
# Calculate rmse

In [13]:
import math

rmse = math.sqrt(mean_squared_error(y_test , y_pred))

rmse

5.712569236646562

In [14]:
# import f_regression

In [15]:
from sklearn.feature_selection import f_regression as fr

In [16]:
result = fr(X , y)


In [17]:
print(result)

(array([1.41905913e+02, 4.57019756e+00, 1.44882087e-03, 1.59990513e-01,
       3.16606568e-03, 4.04208927e-01]), array([1.77038466e-12, 4.14028344e-02, 9.69907241e-01, 6.92200477e-01,
       9.55528076e-01, 5.30086171e-01]))


In [18]:
f_score = result[0]
p_values = result[1]

In [19]:
f_score , p_values

(array([1.41905913e+02, 4.57019756e+00, 1.44882087e-03, 1.59990513e-01,
        3.16606568e-03, 4.04208927e-01]),
 array([1.77038466e-12, 4.14028344e-02, 9.69907241e-01, 6.92200477e-01,
        9.55528076e-01, 5.30086171e-01]))

In [20]:
np.set_printoptions(precision=3, suppress=True)

In [21]:
columns = list(X.columns)

print('  ')
print('  ')
print('  ')

print("   Features ,     F-score     ,     p_values     ")
print("------------ ,  --------------- ,  ---------------  ")
for i in range(0 , len(columns)):
   f1 = "%4.2f" % f_score[i]
   p1 = "%2.6f" % p_values[i]
   print("      " , columns[i].ljust(12) , f1.rjust(8) , "      " , p1.rjust(9))

  
  
  
   Features ,     F-score     ,     p_values     
------------ ,  --------------- ,  ---------------  
       Hours          141.91         0.000000
       sHours           4.57         0.041403
       hoursplayed      0.00         0.969907
       income           0.16         0.692200
       distance         0.00         0.955528
       calories         0.40         0.530086
